logging:
  level: info
  level.com.zt.thrad: debug
server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    name: test
    url: jdbc:oracle:thin:@192.168.16.35:1521:zhuting
    username: zhuting
    password: zhuting123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 30
      max-active: 300
      min-idle: 15
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL


#  MyBatis autoMappingBehavior
mybatis:
  #  实体
  typeAliasesPackage: com.zt.thrad.entity
  #  Mapper
  mapperLocations: classpath:mapper/*.xml

  configuration:
    # 自动装配实体类
    auto-mapping-behavior: full
    #驼峰转换
    mapUnderscoreToCamelCase: true

thread:
  pool:
    max-size: 200
    priority: 8
    queue-capacity: 800
  core-pool-size: 10